// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-1zC4vdFTHmWFCh26jREhCZetfXh9qU',
    appId: '1:148285109899:web:d32893ffb9e05c4b2ac68e',
    messagingSenderId: '148285109899',
    projectId: 'ezpark-5fcf7',
    authDomain: 'ezpark-5fcf7.firebaseapp.com',
    storageBucket: 'ezpark-5fcf7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwC0LkXkfXLz-Mu5uv4Fz-UymAXxv5B7A',
    appId: '1:148285109899:android:870f15870bcd01952ac68e',
    messagingSenderId: '148285109899',
    projectId: 'ezpark-5fcf7',
    storageBucket: 'ezpark-5fcf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA98iRe_0V-cS2mu6umjNqdmWW3mm4WwIA',
    appId: '1:148285109899:ios:8516b19e5183a1802ac68e',
    messagingSenderId: '148285109899',
    projectId: 'ezpark-5fcf7',
    storageBucket: 'ezpark-5fcf7.firebasestorage.app',
    iosClientId: '148285109899-mdkh5tcone1ocarc5gm3len4klfqokah.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezpark',
  );
}
